version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[docker] "

    - package-ecosystem: "pip"
        directory: "/"
        schedule:
        interval: "weekly"
        commit-message:
        # Prefix all commit messages with "[pip] " (no colon, but a trailing whitespace)
        prefix: "[pip] "

