"root_path": "/NaaVRE-workflow-service"
"debug": true
openapi:
  verify_ssl: false
  oidc_configuration_url: "https://naavre-oidc-server/.well-known/openid-configuration"
  disable_oauth: false

vl_config:
  - name: "virtual_lab_1"
    wf_engine: "argo"
    other_config: "value1"
  - name: "virtual_lab_2"
    wf_engine: "other_engine"
    other_config: "value2"