global:
  namespace: naavre

  common:
    userPods:
      extraVolumeMounts:
        - name: naa-vre-public
          mountPath: /home/jovyan/Cloud Storage/naa-vre-public
          readOnly: true
        - name: naa-vre-user-data
          mountPath: /home/jovyan/Cloud Storage/naa-vre-user-data/
          subPath: '{unescaped_username}'


jupyterhub:
  vlabs:
    openlab:
      image:
        tag: latest
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/latest/download/base_image_tags.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-tests
        cell_github_token: ghp_XXXXXXXXXXXXXXXX
        registry_url: ghcr.io/naavre/naavre-cells-vl-tests
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json

#naavreContainerizerService:
#  enabled: false
#
#naavreWorkflowService:
#  enabled: false
#
#k8sSecretCreator:
#  enabled: false