name: Collect tests

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      oidc_configuration_url:
        required: true
        type: string
env:
  DEBUG: ${{ inputs.debug }}
  OIDC_CONFIGURATION_URL: ${{ inputs.oidc_configuration_url }}

jobs:
  collect-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          python-version: 3.11
          path: ${{ env.CONDA }}/envs
          environment-file: environment.yaml
          activate-environment: naavre-workflow-service
          use-mamba: true

      - name: Cache Conda environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-environment-${{ runner.os }}-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            conda-environment-${{ runner.os }}-
        id: cache-conda

      - name: pytest
        shell: bash -l {0}
        run: |
          conda activate naavre-workflow-service
          pip install pytest
          pytest --collect-only -q | grep 'tests/' | jq -R . | jq -s . > test_list.json
          cat test_list.json

      - name: Upload pytest output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_list
          path: test_list.json
