name: Collect tests

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      oidc_configuration_url:
        required: true
        type: string
env:
  DEBUG: ${{ inputs.debug }}
  OIDC_CONFIGURATION_URL: ${{ inputs.oidc_configuration_url }}

jobs:
  collect-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest --collect-only -q | grep 'tests/' | jq -R . | jq -s . > test_list.json
          cat test_list.json

      - name: Upload pytest output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_list
          path: test_list.json
