name: make
on:
  release:
    types: [published]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  configure-workflow:
    name: Configure workflow
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      runner: "ubuntu-latest"
    steps:
      - id: skip_check
        name: Configure skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md"]'  # FIXME
          do_not_skip: '["workflow_dispatch", "schedule", "release"]'

  lint:
    uses: ./.github/workflows/lint.yml
    needs: [ configure-workflow ]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' }}
    with:
      runs-on: ubuntu-latest

  call-pytest:
    uses: ./.github/workflows/run-tests.yml
    needs: [ configure-workflow ]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
    with:
      runs-on: ${{ needs.configure-workflow.outputs.runner }}
      debug: ${{ vars.DEBUG }}

  call-build-container:
    needs: [ configure-workflow,call-pytest ]
    uses: ./.github/workflows/build-container.yml
    with:
      oci_tag: ghcr.io/naavre/naavre-workflow-service
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}

  call-helm-chart-release:
    needs: [ call-build-container,call-pytest ]
    uses: ./.github/workflows/helm-chart-release.yml
    with:
      oci_repo: ghcr.io/naavre/charts
      version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push: ${{ github.event_name == 'release' }}

