name: Run tests


on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      debug:
        required: true
        type: string
      oidc_configuration_url:
        required: true
        type: string
      verify_ssl:
        required: true
        type: string
      disable_auth :
        required: true
        type: string
      root_path:
        required: true
        type: string
      test:
        required: true
        type: string
    secrets:
      auth_token:
        required: true

env:
  DEBUG: ${{ inputs.debug }}
  OIDC_CONFIGURATION_URL: ${{ inputs.oidc_configuration_url }}
  VERIFY_SSL: ${{ inputs.verify_ssl }}
  DISABLE_AUTH: ${{ inputs.disable_auth }}
  ROOT_PATH: ${{ inputs.root_path }}
  AUTH_TOKEN: ${{ secrets.auth_token }}


jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: pytest
        shell: bash -l {0}
        run: |
           pytest ${{ inputs.test }} -s --ignore=docker --ignore=cypress --no-header
