# yaml
name: Run tests

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      debug:
        required: true
        type: string
      test:
        required: true
        type: string
      verify_ssl:
        required: true
        type: string
      disable_auth:
        required: true
        type: string

env:
  DEBUG: ${{ inputs.debug }}
  DISABLE_AUTH: ${{ inputs.disable_auth }}
  VERIFY_SSL: ${{ inputs.verify_ssl }}
  REGISTRY_TOKEN_FOR_TESTS: ${{ secrets.registry_token_for_tests }}
  CELL_GITHUB_TOKEN: ${{ secrets.cell_github_token }}

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - name: start Minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          addons: ingress,ingress-dns
          minikube-version: '1.38.0'

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Run setup-tests.sh
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/NaaVRE/NaaVRE-helm/refs/heads/main/scripts/setup-tests.sh
          chmod +x setup-tests-local.sh
          ./setup-tests-local.sh -f values-deploy-naavre-workflow-service-minikube-github.yaml -d -n -u -p -v 

      - name: Test auth token with python jwt library
        run: |
          pip install pyjwt
          python -c "import jwt; import os; token = os.getenv('AUTH_TOKEN'); decoded = jwt.decode(token, options={'verify_signature': False}); print(decoded)"

      - name: Install pytest
        run: | 
          pip install -r requirements.txt
          pip install pytest

      - name: pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest ${{ inputs.test }} -s --ignore=docker --ignore=cypress --no-header --log-cli-level=DEBUG -vv --tb=long