name: Run tests


on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        type: string
      debug:
        required: true
        type: string

env:
  DEBUG: ${{ inputs.debug }}


jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          addons: ingress,ingress-dns

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Run setup-tests.sh
        shell: bash -l {0}
        run: |
          wget https://raw.githubusercontent.com/NaaVRE/NaaVRE-helm/refs/heads/main/scripts/setup-tests.sh
          chmod +x setup-tests.sh
          ./setup-tests.sh -f ../values-deploy-naavreWorkflowService-minikube-github.yaml

      - run: |
            pip install -r requirements.txt
            pip install pytest


      - name: pytest
        shell: bash -l {0}
        run: |
           pytest -s --ignore=docker --ignore=cypress --no-header
